### ISSUE TITLE
Venues

### ISSUE THREAD

**Issue by quentinberder** [jsconfcn/ShenJS#1]
I am starting to look at the event locations.

**1. Hotel**
深圳香格里拉大酒店(建设路店) http://www.sz-shangrila.com/ which is just beside the railway station with many restaurants, hotels and bars around.
Guys suggest that the hotel located near the sea will be nice but the cost and transportation is not very convenient maybe.
**2. Convention center**
Shenzhen Convention & Exhibition Center http://www.szcec.com/sdlfw/zbfwzy/bhxz/
**3. University** 
Jan proposed that we look for university to hold the event, which could be cheaper in price and different from last three years, two years in hotel and one year in 创智天地 cultural and technical parks.
**4. Technical or cultural parks**

Any idea?

**Comment by clairesheng** [comment]
Here to summarize the requirements of the potential venue:
- Hold 500+ people
- Clean environment& bathroom
- Big area for signing up and sponsor positions, small talk places for participants
- Transportation convenient, restaurants, hotels around
- Nice lighting & projectors & big screens & good acoustic sounds
- Slide presentation can be shown at different places
- Good venue service
- Allow for food delivery 

I will start to contact a few venues to have a better idea of the pros and cons of different places.

**Comment by z4rd** [comment]
I didn't do a deep research, just find where were the past big events held.

1.深圳君悦酒店（winHEC March，2015）
http://www.shenzhen.grand.hyatt.cn/zh-Hans/hotel/home.html
![image](https://cloud.githubusercontent.com/assets/6663547/6121425/2261254c-b11e-11e4-8e3d-f6f4c974cc3f.png)

2.深圳万科国际会议中心(seems near the sea)
http://place.eventown.com.cn/27416.html
![image](https://cloud.githubusercontent.com/assets/6663547/6121300/e7f6f0e2-b11a-11e4-8690-c65707e10573.png)

3.深圳蛇口希尔顿
http://www.hilton.com.cn/SZXSSHI/meeting.html
![image](https://cloud.githubusercontent.com/assets/6663547/6121328/7b3a331e-b11b-11e4-82cf-f8c35efb915b.png)

![image](https://cloud.githubusercontent.com/assets/6663547/6121285/b35687bc-b11a-11e4-88ec-0b7b2f8d0a07.png)

**Comment by erqiudao** [comment]
yeah big screen！

**Comment by erqiudao** [comment]
Allow for food delivery
中文应该叫 简餐 外包 公司 之类的  不太记得了 以前在北京做活动的时候 用过很多次 他们提供餐具 简餐和酒水 还提供1/2个服务员  走的时候会把东西都收走巨方便 啥都不用管  有人搬东西好重要的，深深的记得去年我和claire去超市买苏打水和麦当劳拿10人份左右的午餐都要拎残了。

**Comment by clairesheng** [comment]
This is the amount which Goddy gives us about last year venue in Hangzhou. - ~ 30,000 RMB (venue and some devices for two days) Hilton hotel which in the suburb and he got a preferential price, so...quite a difference.

Shangri-La Hotel http://www.sz-shangrila.com/
![grand ballroom 2 1](https://cloud.githubusercontent.com/assets/6504475/6144264/16f1fe28-b210-11e4-8a02-67ed3da8dad4.jpg)
- Luo Hu Area
- Grand Ball Room：720sqm，4meter-high，60,000/per day（08：00-17：00） 
- Pro: good and convenient location, many adjacent hotels and restaurants.
- Con: Seems not big enough screen, low floor height. 

Grand Hyatt http://www.shenzhen.grand.hyatt.cn/zh-Hans/hotel/home.html
![brand ballroom - meeting setup](https://cloud.githubusercontent.com/assets/6504475/6144284/4c4c8584-b210-11e4-88a5-051a746340b1.JPG)
![foyer](https://cloud.githubusercontent.com/assets/6504475/6144283/4c4c7364-b210-11e4-9534-0739ed603bee.jpg)
![ballroom](https://cloud.githubusercontent.com/assets/6504475/6144285/4c50ead4-b210-11e4-9fe6-f657f82cb16d.jpg)
- Luo Hu Area
- 160,000/ per day 
- Tea break  A. 128+15% service fee/ per，B. 68/per
- Pro: same area, near railway station
- Con:  better projector and screen, help to offer LED screen rental. Have tea break. Quite expensive.
  酒店可提供墙内嵌入式投影屏幕和投影仪供4组，如果您需要LED电子屏幕，酒店为您介绍公关公司，可为您提供LED电子屏幕的租用服务。

**Comment by clairesheng** [comment]
I am contacting other venues, will have more information tomorrow morning.

**Comment by clairesheng** [comment]
3 Hilton Hotel http://www.hilton.com.cn/SZXSSHI/hotel_intro.html Last year it's also Hilton.
- Shekou
- 160,000 per day
- near the sea, nice view
- not far away from Bao An Airport, and pier to Hong Kong
  ![screen shot 2015-02-12 at 4 44 52 pm](https://cloud.githubusercontent.com/assets/6504475/6164222/f6b89fcc-b2d7-11e4-9bd2-a5b9f636fe2d.png)
  ![screen shot 2015-02-12 at 4 45 47 pm](https://cloud.githubusercontent.com/assets/6504475/6164221/f6a8b88c-b2d7-11e4-85e8-0440e8ce32af.png)

4-1 Vanke International Conference Center (Da Mei Sha)
![screen shot 2015-02-12 at 4 26 37 pm](https://cloud.githubusercontent.com/assets/6504475/6164304/cb9c8532-b2d8-11e4-9ad8-dacd0d286e14.png)
Conference Hall
- Near the sea :sunglasses: 
- 80,000 per day
- 460 fixed seats, may need additional seats
- A big popular tourism and entertainment area nearby

**Comment by clairesheng** [comment]
4-2 Vanke International Conference Center (Da Mei Sha)
Banquet Hall 
![screen shot 2015-02-12 at 4 26 21 pm](https://cloud.githubusercontent.com/assets/6504475/6164864/26493a7a-b2de-11e4-9ecb-372c84686942.png)
120, 000 per day for 1200 sqm, half of the space may be enough for us 7, 5000 per day.

Party or Buffet hall
![screen shot 2015-02-12 at 4 26 53 pm](https://cloud.githubusercontent.com/assets/6504475/6165001/482235ba-b2df-11e4-86b2-8e7ec3c55ddb.png)
150 per person

**Comment by z4rd** [comment]
It may take more than three hours from downtown to Vanke International Conference Center....
People held events there seems token lots of measures to ensure the traffic.
http://sz2014.archsummit.com/travel

**Comment by guo-yu** [comment]
Hi guys, Im kind of a insider in hotel loyalty programs. Actually I've three top (mostly) account of each hotel group, such as Starwood(Platinum), IHG(Platinum Royal Ambassador) and Hyatt(Platinum), which may helps.

In fact, I think Grand Hyatt ShenZhen is the best choice in ShenZhen :)
Intercontinental in district Nanshan is good too.
Some other choice are Sheraton Futian, Four Points Futian (by Sheraton), St. Regis (Maybe too expensive) and The Westin in NanShan

**Comment by guo-yu** [comment]
Hilton Shekou is good, but far away from railway station and downtown.

**Comment by guo-yu** [comment]
If budget limited, maybe consider Crowne Plaza Hotel LongGang, it locates in a satellite town by the north side of LuoHu (downtown in ShenZhen), about half a hour range of driving and a half of price. This hotel is a very new hotel have a great hardware and provides shuttle buses

![](http://ww2.sinaimg.cn/large/61ff0de3jw1epb9le3rlyj20dm089q4j.jpg)

**Comment by guo-yu** [comment]
Hyatt Place in LuoHu is good too, but I do not know if it has such a large ballroom to hold 500 people

**Comment by erqiudao** [comment]
wow! :+1:

**Comment by clairesheng** [comment]
@turingou Thank you for your advice. Guo Yu is our last year's speaker. He can help us enquiry and find cheaper and ideal hotels.

**Comment by exdestroyer** [comment]
If hold it in Shenzhen University, I will be happy~ :)

**Comment by markyun** [comment]
I must go this time
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by fraserxu** [comment]
@exdestroyer We'd more prefer to hold the events in a university, but not sure about how and whom to contact, are you a student from Shenzhen University or you know someone we can reach to?

**Comment by fengmk2** [comment]
去年杭 JS 也曾经联系过大学，但是了解到一个行政因素后，就没去找学校的场地了。
学校的场地有一个特殊情况：就算提前几个月预定好的场地，一旦那天学校需要这个场地用来开行政会议，无论谁预定的场地，都得取消让步给行政会议。

**Comment by xeodou** [comment]
@fengmk2 涨姿势了。

**Comment by bencrox** [comment]
我們香港這邊願意大力支持，只要能過境的朋友，我們來承辦 香港科學園一日團，連帶一次 Hackathon 怎看？

**Comment by fraserxu** [comment]
@bencrox Sounds awesome!

**Comment by bencrox** [comment]
@fraserxu 我本部在火炭，其中一家公司示範室在深圳崗廈好百年家居中心，歡迎來會面商談。

**Comment by fraserxu** [comment]
@bencrox Great! We'll have an schedule for a visiting to Shenzhen soon, will let you know!

**Comment by keepanote** [comment]
Big screen！Bigger than bigger.

**Comment by bencrox** [comment]
Just get reply from QianHai , the conference hall can hold 30 tables or 1000 seats.
![image](https://cloud.githubusercontent.com/assets/633181/6405455/98b94de4-be5e-11e4-806d-19c6d465f426.png)
![image](https://cloud.githubusercontent.com/assets/633181/6405458/a0cbdc40-be5e-11e4-9a50-b59ad9276f27.png)
![image](https://cloud.githubusercontent.com/assets/633181/6405467/aaa4144e-be5e-11e4-99f3-e37955016e64.png)

**Comment by fraserxu** [comment]
:+1:

**Comment by clairesheng** [comment]
http://qh.vanke.com/businessservice/  @bencrox Ben, the place looks nice. Any idea what is the price?

**Comment by clairesheng** [comment]
Vanke Enterprise Dream Park.
This is the place where @bencrox proposed. The quote price is 100,000 rmb for 840 seats and 60,000 rmb for 450 seats if separated into half.
![image_1425022244 120487](https://cloud.githubusercontent.com/assets/6504475/6409083/4cff13bc-be99-11e4-9ef3-1caab1dec85b.jpg)
![image_1425022266 982903](https://cloud.githubusercontent.com/assets/6504475/6409084/4d0591f6-be99-11e4-812f-f056d85ade37.jpg)

TenCent multi-function hall. Around 400 seats. 
![cl m6 vn4m 3ie ed_c7](https://cloud.githubusercontent.com/assets/6504475/6409155/7ba995a6-be9a-11e4-91b2-7617d2c206fb.jpg)
![k9 cyw bvddggw_6 80](https://cloud.githubusercontent.com/assets/6504475/6409156/7bafa8b0-be9a-11e4-8ec9-4c191c5c03aa.jpg)
![2 _y 4lgm dqon7fkcrbna](https://cloud.githubusercontent.com/assets/6504475/6409157/7bb4743a-be9a-11e4-9ba4-89de8e37da5c.jpg)

**Comment by clairesheng** [comment]
科兴科学园 Located in Hi-tech Industrial Park, Nanshan District
400seats 20k per day 
![default](https://cloud.githubusercontent.com/assets/6504475/6409284/33c4f300-be9c-11e4-94ec-5c8835d8d1c9.jpg)
![image_1425028179 231766](https://cloud.githubusercontent.com/assets/6504475/6409828/7166a45e-bea3-11e4-8e22-8b38ec31e609.jpg)

600 seats, 25k per day
![image_1425027925 196168](https://cloud.githubusercontent.com/assets/6504475/6409836/99f6d484-bea3-11e4-9738-d17b42efe8cb.jpg)
![image_1425028267 095471](https://cloud.githubusercontent.com/assets/6504475/6409845/a7098766-bea3-11e4-8eca-9e9692bdcd01.jpg)

**Comment by xeodou** [comment]
Looks cheap and nice.
The last one is too long, people can't see anything at the end.

**Comment by guo-yu** [comment]
Diff chart here, price chart on the way.

![diff](http://ww1.sinaimg.cn/large/61ff0de3jw1epo81xqyepj20pa0ezn00.jpg)

![diff2](http://ww1.sinaimg.cn/large/61ff0de3jw1epo82l3281j20ii0evabx.jpg)

**Comment by bencrox** [comment]
@clairesheng I plan to visit and make a big bargain in QianHai. They need to do something.

**Comment by xeodou** [comment]
@turingou Great work !!!

**Comment by guo-yu** [comment]
Just got reply from 4Points by Sheraton(深圳福朋喜来登)

![](http://ww4.sinaimg.cn/large/61ff0de3jw1eprf6llutnj20hr0m2764.jpg)
![](http://ww2.sinaimg.cn/large/61ff0de3jw1eprf6xebsyj20lx0gb44f.jpg)
![](http://ww3.sinaimg.cn/large/61ff0de3jw1eprf779d3oj20om0eogso.jpg)

40k/Day, include a VIP restroom, 525 m^2
![](http://ww3.sinaimg.cn/large/61ff0de3jw1eprf7u7152j20cq02pdgm.jpg)

**Comment by xeodou** [comment]
This is one is good, have a big room. it looks like we have in Hangzhou last year.

**Comment by guo-yu** [comment]
And St.regis ShenZhen, a really nice ballroom, but may be too expensive.

180k / Day (discount available)

![](http://ww1.sinaimg.cn/large/61ff0de3jw1eprfqu4ltaj20df08gq3n.jpg)
![](http://ww4.sinaimg.cn/large/61ff0de3jw1eprffw03yzj20g80d6gp2.jpg)
![](http://ww2.sinaimg.cn/large/61ff0de3jw1eprfalgk61j20jk0iwtae.jpg)

**Comment by guo-yu** [comment]
Grand Hyatt, a quite nice hotel in ShenZhen 

100k / Day

![](http://ww3.sinaimg.cn/large/61ff0de3jw1eprfm5hq3yj20m70gmte8.jpg)
![](http://ww2.sinaimg.cn/large/61ff0de3jw1eprfmue57ij20o808zacq.jpg)

**Comment by xeodou** [comment]
@turingou Looks  4Points by Sheraton is located in HK on Google Map . Does it require VISA ?

**Comment by guo-yu** [comment]
@xeodou 4Points by Sheraton is near by FuTian port, not located in HK :)

**Comment by thoward** [comment]
Anyone look into PangLin Hotel? http://www.panglin-hotel.com/en/meetings_and_weddings.php

Probably out of price range, but Shenzhen Cultural Center has a number of spaces available to lease. I'd like to avoid the boring corporate environments if possible. Instead, venues focused on live performance like music, or stage performances, would be a better fit than "corporate conference center at a hotel".

Thanks,
Troy

**Comment by fraserxu** [comment]
Agree with @thoward . Those events from EU or US have some good examples of hosting besides a beach or even wilds like(campjs), maybe we could have a try.

**Comment by thoward** [comment]
Having the right feeling to the building changes the overall inspiration of the conference. It should feel like a place where art happens, not a place where business happens.

**Comment by guo-yu** [comment]
It reminds me UABB(Bi-city biennale of urbanism and architecture, 深港建筑双年展), it has been hold for a few years in a old glass factory in SheKou harbor (广东浮法玻璃厂/ 蛇口客运码头旧仓库)

**Comment by bencrox** [comment]
I have visit the QianHai area today. It is very impressive and I can make really big bargain, to make the Bureau a sponsor of the Event. So now I would like to ask whether the organisers would like to have a meeting with QH management. 

By the way, who are the organisers?

**Comment by fraserxu** [comment]
@bencrox The Wiredcraft team are currently helping organize things.

We really appreciate your help and we're more than happy to meet the QH management.

We are still trying to contact the local internet companies and making a schedule for the coming visit to Shenzhen. We'll move things fast and hope that won't  take too long. :D

**Comment by quentinberder** [comment]
Don't forget Troy who is giving us support with the international community and his knowledge with event organization. We all have been working on the JavaScript events during the past years.

**Comment by bencrox** [comment]
@fraserxu , @quentinberder would you mind me joining as co-organiser ? 
Apart from the money, I am very experienced in making events:
Consider BarcampHK 2007~2014 each year, and GZ, SZ, Macau, then 
Startup Weekend Hong Kong ( 1~4 ), then StartLab ( HK ). 
I am active in Pearl River Delta, have business in many cities here, and connect to many dev groups.

**Comment by clairesheng** [comment]
PangLin Hotel http://www.panglin-hotel.com/en/
500 seats 44,000/ per day
![penglin-hotel](https://cloud.githubusercontent.com/assets/6504475/6457563/7819b66c-c1b2-11e4-8225-4d182612bd8b.jpg)

**Comment by clairesheng** [comment]
Asked people in Shenzhen and checked some artsy places like
- 南海意库http://www.nhecool.com/Park/Index.html 100-200people
- 深港建筑双年展http://www.szhkbiennale.org/ no electricity and water, too much trouble for us to rearrange the place  
- Loft华侨城创意文化园http://www.octloft.cn/ 100-200people

These are the famous cultural places in Shenzhen. Who knows any other possible artsy places?

**Comment by quentinberder** [comment]
@bencrox could we have a talk tomorrow to discuss things? Just ping me on the Slack channel https://shenjs.herokuapp.com/.

**Comment by clairesheng** [comment]
Huaxia Art Center, located in the downtown http://www.octeshow.com/show5.aspx 
There is a 900 seats theater. Price is 50k per day, need to rent projector equipment.
![huaxia art center](https://cloud.githubusercontent.com/assets/6504475/6478402/1590545e-c26d-11e4-9283-e64bb0c4b82a.jpg)

**Comment by clairesheng** [comment]
To summarize the possible venues for now:

Huaxia Art Center  http://www.octeshow.com/show5.aspx 50k per day, 900 seats

Vanke Enterprise Dream Park http://qh.vanke.com/businessservice/ 100k, 800 seats/ 60k, 450 seats (may have a discount)
Hi-tech Park Convention Center 600seats, 25k

4Points by Sheraton http://www.four-hotel.com/jdtp.html 40k, 500seats
Shangrila (Luohu)  http://www.sz-shangrila.com/ 60k, 500seats
Panglin http://www.panglin-hotel.com/en/ 44k, 500seats

**Comment by xeodou** [comment]
http://www.octeshow.com/show5.aspx  it's too long and narrow. It's good for some show with different level tickets.
http://qh.vanke.com/businessservice/ is a good choice. But the information is not too much, Where should we get the more pictures.
 http://www.four-hotel.com/jdtp.html  is good, we have have after part at the rooftop. If no company want hold this. And if we can get a good price.
 http://www.sz-shangrila.com/  is like 4Points but this one is more expensive and without rooftop.
 http://www.panglin-hotel.com/en/  located in city center.

I prefer 4Points ,  if we can we want have a cool place like art center, but it;s hard to find. And in a hotel is much easier. If the venues is just so so, we can make the conference be cool. And i think we can do that.

**Comment by exdestroyer** [comment]
@fraserxu  yes I am a graduate from SZU, if you want to hold it in SZU, I may help you find the professor in our college

**Comment by fraserxu** [comment]
@exdestroyer That would be awesome. How can I reach to you? I may have some questions and hope you would help.

My email is xvfeng123ATgmail.com or fraserxuATwiredcraft.com

**Comment by clairesheng** [comment]
http://www.ocat.org.cn/index.php/About
It's in OCT-LOFT.  No wifi and projector, but with air conditioning. Price is 100k per day. I'm not sure it's good, but we can give a visit.
![dsc05004](https://cloud.githubusercontent.com/assets/6504475/6613304/9290357e-c8c5-11e4-8175-b0bd9d571685.JPG)
![ocat-photo_2](https://cloud.githubusercontent.com/assets/6504475/6613305/929663c2-c8c5-11e4-816d-c038a3030ebc.jpg)
![ocat a](https://cloud.githubusercontent.com/assets/6504475/6613306/9297067e-c8c5-11e4-82e6-5a9a00fd497f.jpg)
![13](https://cloud.githubusercontent.com/assets/6504475/6613307/92a910a8-c8c5-11e4-8c6e-91db4b626a3b.JPG)

**Comment by fraserxu** [comment]
This place could work as soon as we can set up a good projector, and of course wifi.

**Comment by clairesheng** [comment]
Shenzhen university 500-people conference hall ![6 pic](https://cloud.githubusercontent.com/assets/6504475/6799036/84a4d3c0-d24d-11e4-8762-e1826e2cebaa.jpg)

8000 rental fee for 2 days. They stop renting the place from July since the students and teachers started their holiday. Checking with their  student union what dates are available for rental.

**Comment by xeodou** [comment]
The wifi stuff and make sure there is no rule, if some **administrative conference** coming we need give back the venue back with no doubt.  
Personally i don't like the large ladder venues.

**Comment by bencrox** [comment]
@clairesheng I am still waiting your reply / arrangement in slack. QH venue can be fully sponsored in our proposed time. Need co-ordination before any step further :P

**Comment by fraserxu** [comment]
@bencrox Sorry for the delay(been busy on client work recently). We've just set the date to visit Shenzhen from April 8 to April 10(right after the Qingming festival).

Not sure if that time is feasible for you to schedule a potential face to face meet with you. We're more that happy to talk to the QH team if you can go with us or set a schedule for us(if you are busy).

That could save us lots of budget so we can spend it on other stuff which could benefit for the developers.

Also, we're making a list of companies that we'd like to visit when we're there(Seeedstudio for example(we'd like to have a node-bot session and want them to sponsor for some hardware :D)).

Seems that you have lots of friends there, if you'd share some of them, that would be awesome!

**Comment by bencrox** [comment]
I am OK for that period. Just want to make sure we can arrange before that

**Comment by fraserxu** [comment]
Cool! Then can you please set a proper date for us?  Thanks!

**Comment by quentinberder** [comment]
We went with QH. Closing.
