### ISSUE TITLE
Ideas for goodies

### ISSUE THREAD

**Issue by quentinberder** [jsconfcn/ShenJS#10]
Having some goodies (if the budget allows it) will be a good thing to:
- Have a stronger impact on the crowd
- Make this event impactful
- Let the non attendees look forward for future events
- Have fun while hacking/coding

Due to the particularities of Shenzhen, we should have a part of the conference oriented to some hardware. Something like an arduino or raspberry pi would fit perfectly.

We could:
- Have a room dedicated to hacking those
- Have speakers covering those topics

Thoughts?

**Comment by bencrox** [comment]
Js driven toys. Let's see what we can do.

**Comment by quentinberder** [comment]
We got everything needed. Closing.
