### ISSUE TITLE
Mailing list

### ISSUE THREAD

**Issue by clairesheng** [jsconfcn/ShenJS#11]
After the ShenJS website goes online, we should send email to inform people.

Here's the addresses of the mailing list to get subscription:
- 3 year participants (Headin should have the email address)
- Sponsors 
- Speakers
- Private message on Weibo

Except collecting the recipients information, we need to have the content and design of the mail.

**Comment by thoward** [comment]
Looks like the landing page has a signup that goes to a Wiredcraft Mailchimp account. Can someone share that login with me in a secure manner? I have a mailing list (~500ppl) for previous years under a different account. This is not the entire list, but it's a substantial portion.

Traditionally, I have managed sending email announcements via that list. We should merge them all under a "jsconf.cn" list and manage it in a single place.

**Comment by quentinberder** [comment]
Sounds good, let's loop back on this Thursday.

**Comment by quentinberder** [comment]
We merged them and have them in a Mailchimp account. Closing.
