### ISSUE TITLE
Review Chinese copy

### ISSUE THREAD

**Issue by hunvreus** [jsconfcn/ShenJS#12]
Just pushed the bilingual version of the site and put raw Google translate strings in there.

You need to review 2 files:
- https://github.com/jsconfcn/ShenJS/blob/master/templates/partials/_subscribe.html (the variables are the top, they are for the placeholder and label of the submit button in the subscribe form).
- https://github.com/jsconfcn/ShenJS/blob/master/source/index.md (the bulk of the copy)

**Comment by quentinberder** [comment]
Reviewed, updated and pushed. Closing. http://2015.jsconf.cn/
