### ISSUE TITLE
Moleskine notebook

### ISSUE THREAD

**Issue by clairesheng** [jsconfcn/ShenJS#13]
We will distribute Moleskine notebooks to the participants for marketing purpose.
- Size: A6 90*140mm, pocket size
- Cover: "JSConf China" logo
- Front 2 pages: Introduce Who we are/ What we do/ Contact information

![moleskine 2](https://cloud.githubusercontent.com/assets/6504475/6208461/65a9fcf0-b5f3-11e4-961b-4c4704e485ca.jpg)

**Comment by hunvreus** [comment]
I didn't mean moleskine notebooks necessary. Just notebooks. The one I had received a while ago was from Phase 2, it was about a fourth of the pages you have in the small moleskine I gave you, and it was printed on recycled paper.

The cover had the conference logo and the inside 2 first pages (back of the cover and first page) where filled with marketing content for the company: logo, pitch, contact info.

**Comment by erqiudao** [comment]
![screen shot 2015-02-16 at 3 56 45 pm](https://cloud.githubusercontent.com/assets/195066/6208520/7d5e5c6e-b5f4-11e4-9cb4-dae117ffb4c1.png)
like this?

**Comment by z4rd** [comment]
I like sketchbook with dot grid !!!!!!

**Comment by clairesheng** [comment]
The cover one thing I am worried about is the color difference and the other, the manufacturer imprints the logo with the color of the book, no white color. 压印logo，没有白色。

**Comment by erqiudao** [comment]
![screen shot 2015-02-16 at 5 13 32 pm](https://cloud.githubusercontent.com/assets/195066/6209284/2bbbddcc-b5ff-11e4-9e67-8293039e8ebc.png)

**Comment by hunvreus** [comment]
Should be fine. We can talk about it later.

**Comment by z4rd** [comment]
Something different and cool!
http://www.frizzifrizzi.it/2014/06/09/inspiration-pad-e-le-righe-matte-che-ti-guidano-nel-magico-mondo-della-scrittura/

![image](https://cloud.githubusercontent.com/assets/6663547/6444868/6c2089a2-c13b-11e4-8b6e-9fee72a9b5c6.jpg)
![image](https://cloud.githubusercontent.com/assets/6663547/6444872/6c7e7ca6-c13b-11e4-955c-10af70a5938c.jpg)
![image](https://cloud.githubusercontent.com/assets/6663547/6444873/6c809a54-c13b-11e4-9d98-dc56f6aebbdc.jpg)

**Comment by quentinberder** [comment]
Closing.
