### ISSUE TITLE
Want Co-organizer in HK ?

### ISSUE THREAD

**Issue by bencrox** [jsconfcn/ShenJS#15]
Hi, this is Ben Crox from HK

I have been doing BarcampHK and events in SZ / GZ / Macau for years. Would 100% like to support JSConf SZ.

Many of you may know I am working out JSConf HK ( Oct 2015 ). I am OK to join meeting in SZ or anywhere nearby. 

I teach people to use MeteorJS as well. Long time server side JS developer. :D

**Comment by gilbertwat** [comment]
Hi, this is Gilbert from HK too

am JS dev full time at looppulse on MeteorJS and iBeacon. Also a co-organizer of JS Conf Asia in HK this year.

+1 for working alongside @bencrox, he is resourceful and well connected in HK, SZ and Mynamar.

am also 100% support JS Conf in China and hope to connect JS community worldwide.

**Comment by erqiudao** [comment]
HK！！！！！！！！！

**Comment by bencrox** [comment]
@erqiudao No surprise. I have been asking peers and hope to bring JSConf.cn 2015 to HK as well. It is not bad to have it in SZ. Let's make things happen!

**Comment by quentinberder** [comment]
Done, closing.
