### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by thoward** [jsconfcn/ShenJS#16]
Landing page does not have a Code of Conduct. We should have this available in English and Chinese. Previous year's COC is available here: http://2013.jsconf.cn/code-of-conduct.html (somehow we missed this in 2014? Yikes!)

**Comment by hueitan** [comment]
Should include COC! +1 :+1:

**Comment by fraserxu** [comment]
We will add this by the weekend.

**Comment by quentinberder** [comment]
It has been added, http://2015.jsconf.cn/code-of-conduct-en/. Closing.
