### ISSUE TITLE
List of potential international speakers

### ISSUE THREAD

**Issue by fraserxu** [jsconfcn/ShenJS#18]
### ES6([babel](https://github.com/babel/babel))
- Co-author Sebastian McKenzie [@sebmck](https://github.com/sebmck) 
- [Babel contributors](https://github.com/babel/babel/graphs/contributors)
### [io.js](https://iojs.org/en/index.html)
- [Rod Vagg](https://github.com/rvagg), [Fedor Indutny](https://github.com/indutny), [isaacs](https://github.com/isaacs)...
- [iojs.cn](https://github.com/iojs/iojs-cn/graphs/contributors)
- [io.js contributors](https://github.com/iojs/io.js/graphs/contributors)
### Web frameworks(React.js, Angular.js, Meteor.js, Koa.js)
- [React.js contributors](https://github.com/facebook/react/graphs/contributors)
- [Angular.js contributors](https://github.com/angular/angular.js)
- [Meteor.js contributors](https://github.com/meteor/meteor)
- [Koa.js contributors](https://github.com/koajs/koa)
### Real time communication(WebRTC, xmpp-ftw)
- torrent magic [mafintosh](https://github.com/mafintosh)
- web torrent, standard [feross](https://github.com/feross)
### [Node-bots](http://nodebots.io/)(arduino, [Johny Five](https://github.com/rwaldron/johnny-five), tessel & hardware)
- johny-five co-contributors [Rick Waldron](https://github.com/rwaldron)
- [johny-five contributors](https://github.com/rwaldron/johnny-five/graphs/contributors)
### Cross platform development([React Native](http://facebook.github.io/react-native/), node-webkit, atom-shell, phonegap, ionic)
- [react-native](https://github.com/facebook/react-native) [contributors](https://github.com/facebook/react-native/graphs/contributors)
- [ionic contributors](https://github.com/driftyco/ionic/graphs/contributors)
- [atom-shell](https://github.com/atom/atom-shell)
- [nw.js](https://github.com/nwjs/nw.js)
### Mad science(torrent, dat)
- torrent magic [mafintosh](https://github.com/mafintosh)
- web torrent, standard [feross](https://github.com/feross)
- [dat](https://github.com/maxogden/dat) [maxogden](https://github.com/maxogden)
### Microservices, NodeOS
- [NodeOS](https://github.com/NodeOS/NodeOS)

**Comment by hunvreus** [comment]
Have we contacted any of these?

**Comment by fraserxu** [comment]
Not yet.

**Comment by xeodou** [comment]
I have contact node_xmpp_ftw author @lloydwatkin
He said he like to give a talk if he has some time, he is in Africa right now. 
When does CFP close , by the way ?

**Comment by fraserxu** [comment]
@xeodou  We haven't set the closing date yet(as we haven't really start to contact international speaker yet).

Yes we should start this as soon as possible. Hope this list will help to make some progress here.

**Comment by xeodou** [comment]
That's cool. Let's do this.

**Comment by popomore** [comment]
npm @othiym23

**Comment by thefoxis** [comment]
Um. Have you thought about reaching out to _any_ women? Raquel has a pretty [impressive list](https://twitter.com/rockbot/lists/women-who-node/members) of women doing Node. I have quite [a few recommendations](https://gist.github.com/thefoxis/39f2d562b44b8e6f3fbd) myself.

**Comment by quentinberder** [comment]
@thefoxis yes we did contact some women speakers. Thanks a lot for both lists, we will get in touch and see if any are interested to join us.

**Comment by xeodou** [comment]
@thefoxis Thanks for your suggestion,Yes we have think about it and we are start to touch some women developer in China, And we also welcome some foreigner women speakers.
By the way @thefoxis would you like to submit a topic if you have some js stuff want share.

**Comment by thefoxis** [comment]
@quentinberder @xeodou&mdash;happy to make more specific recommendations if you want to have particular topics covered :smiley_cat: 

btw. if you're thinking abour WebRTC you should definitely talk to @fippo and @henrikjoreteg.

@xeodou&mdash;I was thinking about submitting, yes. Lately I've been doing more community related talks though—like this one closing [CSSConf.eu](https://www.youtube.com/watch?v=ZlxpF9taprI) or opening [ForwardJS](https://www.youtube.com/watch?v=OCbO-u43xNk). I really enjoy that + it resonates very well with audiences, especially with communities outside of US. Also all the JSConf family events historically have been the best venues for these types of talks. 

However I've done technical talks at JSConf.eu and other events as well, but they were more high-level, architecture and approach ones. I do some JS/Node, but my main occupation is still front-end :v: Not sure if that's what you're looking for as well?

**Comment by lloydwatkin** [comment]
100x @fippo for webrtc :)

**Comment by thefoxis** [comment]
re: [this conversation](https://twitter.com/mrmrs_/status/597712804657827840), @geelen gave an [awesome talk](https://twitter.com/glenmaddern/status/596308706632937474) at Front Trends last week on JSPM and [Adam Morse](twitter.com/mrmrs_) is just the smartest.

**Comment by xeodou** [comment]
@thefoxis We are trying to bring the best programer around the world to the JavaScript Conference.  All topics about the JavaScript is welcome, it doesn't matter either front-end or back-end.

**Comment by quentinberder** [comment]
The speaker list was decided by the community and posted on the site http://2015.jsconf.cn/ . Closing.
