### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by quentinberder** [jsconfcn/ShenJS#2]
After talked with Ronan,we made some changes about the design
**Color**
First is the blue color,we found a nice blue color on dribbble,https://dribbble.com/shots/1905177-7-line-illustrations-for-Workangel?list=users&offset=1
![alltogether](https://cloud.githubusercontent.com/assets/195066/6054648/1bc76b20-ad2b-11e4-95c8-ef695ddfea8e.png)

**Landing**
The call for action is to subscribe,so we move that part up,and put count down above to make a  scarcity technique for marketing.
in the hero part,we use famous building stand for shenzhen like HangJS,it's well-known and fraser recognize them Immediately. And we can use it as a  pattern for flyer/docs/KT board and other VI staff.
Ronan suggests us use some JS effect for the hero,like:http://matthew.wagerfield.com/parallax/
![screen shot 2015-02-05 at 12 09 39 pm](https://cloud.githubusercontent.com/assets/195066/6054928/e5ff19de-ad2f-11e4-94b8-c0232d2186c3.png)
3 or 4 layers of buildings with clouds  move subtlely

![artboard 7](https://cloud.githubusercontent.com/assets/195066/6054629/dc919b4c-ad2a-11e4-9c64-5d6dbea0cc56.png)

**Hero in landing page**
for The parallax effect  http://matthew.wagerfield.com/parallax/ 
I separate the building into 3 layers,and export them in dropbox/.../shenjs/img
![screen shot 2015-02-05 at 3 21 58 pm](https://cloud.githubusercontent.com/assets/195066/6056372/dcea6fe0-ad4a-11e4-8bbf-6a9bf0648491.png)
![screen shot 2015-02-05 at 3 22 18 pm](https://cloud.githubusercontent.com/assets/195066/6056373/dcec7fe2-ad4a-11e4-84fd-3250bf580e1e.png)

**Comment by erqiudao** [comment]
Thanks for the feedback from everyone.
working on the new landing page now.
1.Change logo
2.Change the primary blue 
3.Add navigation
4.Add speakers / schedule / Sponsors / Media Partner / Map parts.

Here are screenshots for the mockup.
![screen shot 2015-04-01 at 4 28 00 pm](https://cloud.githubusercontent.com/assets/195066/6937236/a02808de-d88c-11e4-9264-e78d8d5eef9e.png)

![screen shot 2015-04-01 at 4 27 40 pm](https://cloud.githubusercontent.com/assets/195066/6937235/9feaf08e-d88c-11e4-8965-8d287fd1d510.png)

Tell me what you think~ Thanks~

**Comment by hunvreus** [comment]
Pretty good, better direction IMHO. Two things:
- I'm not sure about the 2 different shades of blue, I'd stick with the blue we have in the header and avoid the "facebook" blue altogether.
- We may want to use a picture in the header (black and white, or simply shades of blue).

A good example of a more mature site: http://saltconf.com/

**Comment by z4rd** [comment]
The color schemes, maybe should be more mature/geek. not sure this colorful..

**Comment by erqiudao** [comment]
When we gather the reference,some of the geeks like this website's style
![screen shot 2015-04-02 at 3 14 23 pm](https://cloud.githubusercontent.com/assets/195066/6959386/fb4f0eba-d94a-11e4-8df1-1f5b2d68323b.png)
and some like mature style.
there are more than 500 people in the conference with different country,age,aesthetic,to keep balance,I prefer neutral colors which is not too cold or not too warm.
p.s. I think picture in the header will be great,will try later~

**Comment by bencrox** [comment]
I kinda hope that discussion can be consolidated in Slack. 
Anyway, bravo to the parallax people and pixel artists.

**Comment by quentinberder** [comment]
Done, closing.
