### ISSUE TITLE
CSDN Media Support

### ISSUE THREAD

**Issue by tuhaihe** [jsconfcn/ShenJS#20]
Hi,各位 ShenJS 的组织者，

我是来自 CSDN 的王殿进，在微博上看到有本次活动相关消息。不知道我们本次活动是否会有媒体合作伙伴等事项？如果可以的话，CSDN 计划成为本次活动的媒体合作伙伴。我们可以提供：
- 活动推广宣传（主站/微博、CSDN 相关专家群等）
- 采访：如果有好的话题，我们可以对嘉宾做采访；
- 幻灯分享（可以在 CSDN 下载分享，帮忙传播）

此外，还可以尝试专题报道等形式吧，这个需要具体接洽。

不知道各位组织者觉得如何？

**Comment by xeodou** [comment]
@tuhaihe 欢迎 欢迎, 不过不知道你们 CSDN 对JavaScripts 社区关注的情况如何？因为 CSDN 在很多人看来都是偏向Java之类的语言较多。

**Comment by tuhaihe** [comment]
@xeodou @clairesheng  感谢两位大大。
我稍后给两位发封邮件，然后把这边具体负责跟进的同事介绍给各位。大家来协调。

:)

**Comment by quentinberder** [comment]
Done, closing.
