### ISSUE TITLE
Volunteers

### ISSUE THREAD

**Issue by quentinberder** [jsconfcn/ShenJS#21]
As we did for the other years we will need some volunteers to take care of the foreign speakers when in Shenzhen. We will propose to english speaking students only to join us and we will need to provide them with:
- [ ] Guideline
- [ ] Getting started pouch
- [ ] Support checklist

**Comment by bencrox** [comment]
I will check out help many of HK people will join the helper team.

**Comment by quentinberder** [comment]
@clairesheng prepare and send a Weibo post to ask the community. Ask as well on Twitter (check with Katie for content).

**Comment by floraJ** [comment]
If I want to be a volunteer,what should I do?

**Comment by quentinberder** [comment]
@floraJ sorry for the slight delay, we were working hard on settling the last details. You can directly speak to us on Slack (https://shenjs.herokuapp.com/) or send us an email to support@jsconf.cn

**Comment by quentinberder** [comment]
https://hackpad.com/Volunteer-text-TV7vrT93CJY

**Comment by quentinberder** [comment]
Starting the content.

**Comment by fraserxu** [comment]
Confirmed with @jiangplus for Mathias Buus . He's with substack last year and kind of knowing what he need to do.

**Comment by binggg** [comment]
ok，thank you

**Comment by jiangplus** [comment]
confirmed volunteers:

安小强
韩以纯
景风风(female)

**Comment by fraserxu** [comment]
:+1:

**Comment by binggg** [comment]
:+1:

**Comment by fraserxu** [comment]
@jiangplus You forgot yourself!

**Comment by fraserxu** [comment]
| Name | Departure | Arrival | Flight | Votunteer |
| --- | --- | --- | --- | --- |
| Martin Nauman | July 9 8:55 PM | July 10 8:35 PM | CZ3961 | Azriel |
| Mathies Buus Madson | / | July 10 2:40 PM | CA1313 | @jiangplus |
| Alexandre Strzelewicz | July 9 1:50 PM | July 10 11:50 AM | 东航 5335 | Berry |
| Andrew Fisher | / | / | / | Fraser Xu |
| Tim Pietrusky |  |  |  |  |
| Brian Holt |  |  |  |  |

**Comment by bencrox** [comment]
Do we need to follow up for those go via HK ?

On Tue, Jul 7, 2015 at 12:43 PM, Fraser Xu notifications@github.com wrote:

>  Name Departure Arrival Flight Votunteer   Martin Nauman July 9 8:55 PM July
> 10 8:35 PM CZ3961  Mathies Buus Madson / July 10 2:40 PM CA1313  Alexandre
> Strzelewicz July 9 1:50 PM July 10 11:50 AM 东航 5335  Andrew Fisher / / / Fraser
> Xu  Tim Pietrusky    Brian Holt
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jsconfcn/ShenJS/issues/21#issuecomment-119071187.

## 

Ben Crox, Startup Advocate. @bencrox, Tel: +852 3111 5191

**Comment by fraserxu** [comment]
@bencrox Thanks. Andrew Fisher will go via HK, but I think he has arranged his schedule. I'll let you know if we need your help!

**Comment by bencrox** [comment]
Thank you

On Tue, Jul 7, 2015 at 1:42 PM, Fraser Xu notifications@github.com wrote:

> @bencrox https://github.com/bencrox Thanks. Andrew Fisher will go via
> HK, but I think he has arranged his schedule. I'll let you know if we need
> your help!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jsconfcn/ShenJS/issues/21#issuecomment-119078970.

## 

Ben Crox, Startup Advocate. @bencrox, Tel: +852 3111 5191

**Comment by Axighi** [comment]
Pain's real name is Azriel

**Comment by fraserxu** [comment]
Updated.
