### ISSUE TITLE
Floor plan of the venue

### ISSUE THREAD

**Issue by quentinberder** [jsconfcn/ShenJS#25]
We need to gather the floor plan and prepare the following:
- Map display
- Mapping of the sponsors booth
- Outline of emergency exits
- Plan for after party

**Comment by z4rd** [comment]
trying to find some nearest venue for the second day after party
1.3W tech coffee, inside the park
fraser said he and claire went there before
no sure how many people they can hold.
can't find any details online.

2.[Maan-Coffee](http://www.yunspace.com.cn/service_info/1210.html), 2.6mile, 30min for walk
can hold 150 people
http://www.yunspace.com.cn/service_info/1210.html

**Comment by fraserxu** [comment]
To make things easier, we can choose 3W coffee. Plus we have their contact information.

**Comment by erqiudao** [comment]
Do we need to add contact info on the website? after decide.
and is the photo booth indoor or outdoor?
![screen shot 2015-06-25 at 4 56 01 pm](https://cloud.githubusercontent.com/assets/195066/8350793/1ecde224-1b5b-11e5-8c8d-e79b16eb8d6c.png)

**Comment by z4rd** [comment]
We already have `wechat group` as a contact method on website.
and `staff contact information`(Claire Sheng) in `code of contact` page.
I think it's enough.

**Comment by erqiudao** [comment]
So 600 people ask claire for the after party address?

**Comment by erqiudao** [comment]
![screen shot 2015-06-25 at 5 14 42 pm](https://cloud.githubusercontent.com/assets/195066/8351148/b3482426-1b5d-11e5-9250-b5397164355b.png)
I think we can just put the name of the place in the author place,right?

**Comment by fraserxu** [comment]
We can make it as "3W coffee" now. And if it's changed, we can announce during the conference. What do yo think?

**Comment by z4rd** [comment]
weibo/twitter/website/wechat/the host/people who site behind them
