### ISSUE TITLE
Lucky Draw

### ISSUE THREAD

**Issue by clairesheng** [jsconfcn/ShenJS#27]
The presents of lucky draw for now as follows. We have twice lucky draw each day in day time and more in Afterparty.
- Baidu EChart
  - 小米路由器x2
  - 小米电源x4
  - 蓝牙键盘x1
  - 便携式存储器x1
  - Instax mini8相机
- OneAPM
  - 手机支架x600
  - 玩偶x10
  - 蓝牙音箱x5
  - 笔记本x5
- 阿里云
  - 25份代金券，共7000元
- IT-Consult
  - Rasperryx2
- 七牛
  - 提供 10 至 20 张代金券,每张面额 200 元人民币
- UCloud
  - 价值 100 元面额的代金券 90 张和价值 200 元面额的代金券 10 张
- 图灵
  - 书x100
- 北京邮电
  - 书x97
- Broadview
  - 书x50
- WebStorm
  - 优惠码x12
- Nodebots
  - Two nodebots book
  - coupon 20% off

**Comment by yedeying** [comment]
请问阿里云代金券发放了吗

**Comment by JacksonTian** [comment]
主办方还没有给到我名单。

**Comment by fraserxu** [comment]
@JacksonTian 朴灵老师刚刚发你邮箱了,请查收，谢谢！

**Comment by zhongxingdou** [comment]
WebStorm优惠码啥时候发

**Comment by fraserxu** [comment]
@zhongxingdou 你的邮箱可以发我一下吗？ 我把webstorm的优惠码给你。
