### ISSUE TITLE
Sponsorship documentation

### ISSUE THREAD

**Issue by quentinberder** [jsconfcn/ShenJS#3]
**Docs**
pdf is in dropbox/.../shenjs/doc.pdf
We can proofread the copy.
There are the screenshots.
![doc-01](https://cloud.githubusercontent.com/assets/195066/6056549/8914b490-ad4d-11e4-9481-e66ccbcc195a.png)
![doc-02](https://cloud.githubusercontent.com/assets/195066/6056550/893e62ea-ad4d-11e4-84e7-7e280f3422fc.png)
![doc-03](https://cloud.githubusercontent.com/assets/195066/6056552/89417e08-ad4d-11e4-93cd-190f8576f622.png)
![doc-04](https://cloud.githubusercontent.com/assets/195066/6056553/8942658e-ad4d-11e4-8514-9899aced5b55.png)
![doc-05](https://cloud.githubusercontent.com/assets/195066/6056551/8940c2ba-ad4d-11e4-89d1-8fb94ac95602.png)
![doc-06](https://cloud.githubusercontent.com/assets/195066/6056555/89453d90-ad4d-11e4-86c6-7f446a06e7f3.png)
![doc-07](https://cloud.githubusercontent.com/assets/195066/6056554/89450230-ad4d-11e4-89f6-da49eec31735.png)
![doc-08](https://cloud.githubusercontent.com/assets/195066/6056556/896e4a14-ad4d-11e4-95a8-cbb9249d9fc1.png)
![doc-09](https://cloud.githubusercontent.com/assets/195066/6056557/897152c2-ad4d-11e4-8ba7-60259d808cfd.png)
![doc-10](https://cloud.githubusercontent.com/assets/195066/6056559/897377e6-ad4d-11e4-8b99-550d17d440bf.png)
![doc-11](https://cloud.githubusercontent.com/assets/195066/6056558/8971fff6-ad4d-11e4-9c37-e32bb4ea0fb1.png)
![doc-12](https://cloud.githubusercontent.com/assets/195066/6056561/897821b0-ad4d-11e4-904c-7e63a9b0dcf5.png)
![doc-13](https://cloud.githubusercontent.com/assets/195066/6056560/8974bf3e-ad4d-11e4-95c5-ffe7628dea0f.png)

**Comment by quentinberder** [comment]
Done,font size for content of the table and left column width is a little bit difficult because of the size of canvas.
![doc-10](https://cloud.githubusercontent.com/assets/195066/6057169/da3e9e50-ad55-11e4-974c-8a863c8544ce.png)
![doc-11](https://cloud.githubusercontent.com/assets/195066/6057170/da43362c-ad55-11e4-9ee5-d43b772e8386.png)

**Comment by xeodou** [comment]
Maybe we need change the money from rmb to dollars in English?

**Comment by bencrox** [comment]
不管怎的，這裹代表香港 WebFus 先填一個 TypeA 50k RMB 的坑。誰開戶口和發票給我？

**Comment by xeodou** [comment]
@clairesheng have a look.

**Comment by clairesheng** [comment]
@bencrox 能否给我你的邮箱？我可以进一步跟进发票等细节。

**Comment by fengmk2** [comment]
@bencrox :+1: 哈哈，看来 twitter 不错，算是第一个大陆外赞助了。

**Comment by bencrox** [comment]
@clairesheng  能發到 Gmail 就 bencrox@Gmail ，不然就 info@vernant.so （對，點 SO ）

**Comment by thoward** [comment]
Where is the source for this doc? Can I have access to fix the English content? I'll adjust pricing for international audience. Traditionally, we've kept the invoicing and account separate for international sponsors, using that to pay for costs for international travel/etc, then settle at the end of the conf, leaving any surplus in the account in China. I think we should do that again this year. 

@fengmk2 Twitter will likely be interested in sponsoring this year. I can follow up.

**Comment by bencrox** [comment]
＠thoward will you also help to bridge me with Twitter. I am organize JSConf in HK.

**Comment by quentinberder** [comment]
Done, closing.
