### ISSUE TITLE
请问是否可以参考网站的设计风格？

### ISSUE THREAD

**Issue by numbbbbb** [jsconfcn/ShenJS#35]
我们也在筹备一次大会，非常喜欢深JS官网简洁大方的设计。不知道是否可以参考？
这个repo没有选择license，按照GitHub的说明，这表示repo代码保留所有权利。
我们不会复制代码，会编写我们自己的代码并开源，只是想了解是否可以参考官网的风格。

**Comment by fraserxu** [comment]
抱歉我们之前也没有考虑过这个问题。

原则上来讲是没有问题的，我这下加个MIT的license去。

我们不介意你们借去参考，都是做开源的活动就没关系。要是你们能在网站上稍微注明一下就更好了。

**Comment by wwayne** [comment]
humm, 我知道你, 这位是swift文档同步翻译的发起者, 刚好我最近一直在看swift中文文档。
网站是 @erqiudao 和 @z4rd 设计制作的，得给她们乐乐
也再给你的各种swift同步翻译点个赞 :+1:

**Comment by numbbbbb** [comment]
非常感谢两位！一定会注明设计师和来源。做活动没有专业的设计师确实不行，我们也要努力去找一位了😄

**Comment by fraserxu** [comment]
:+1:
