### ISSUE TITLE
jsconf的发票始终没有收到

### ISSUE THREAD

**Issue by treblam** [jsconfcn/ShenJS#36]
发票始终没有收到，邮件发出去也没有人回复，客服电话也没有，这种服务态度以后怎么敢参加。看到这个请联系我电话：15817473160，或给我邮件：treblam@gmail.com。

**Comment by treblam** [comment]
没有任何回复就直接关闭是什么意思？

**Comment by alsotang** [comment]
感觉这类大会的某些部分还是得外包出去给相关公司啊。发票的问题我都看了两个月了。

**Comment by bencrox** [comment]
愛莫能助，我方還是會在深圳搞開發者活動，已經把這次發票狀況深深記著了，
往後我們承辦時會預先準備。

2015-09-06 10:04 GMT+08:00 alsotang notifications@github.com:

> 感觉这类大会的某些部分还是得外包出去给相关公司啊。发票的问题我都看了两个月了。
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jsconfcn/ShenJS/issues/36#issuecomment-138024924.

## 

Ben Crox, Startup Advocate. @bencrox, Tel: +852 3111 5191

**Comment by fraserxu** [comment]
1. 目前为止暂未收到该邮箱发来的任何邮件;
2. “客服电话也没有” － 这是一个非赢利性质的大会，不存在任何形式的“客服人员以及客服电话”；
3. “这种服务态度以后怎么敢参加” －同上。你的态度决定了我们对你的态度。

**Comment by treblam** [comment]
@fraserxu 我之前发给你的是用公司邮箱发的，xiexiongbiao@mucfc.com
，请查找这封邮件的记录。我在github留的是我的私人邮箱。

2015-09-06 10:35 GMT+08:00 Fraser Xu <notifications@github.com>:

**Comment by erqiudao** [comment]
感谢@alsotang的建议，这个问题我们也意识到了，我们并没有选择外包给PR公司是为了将资金更多用于大会本身而不是在中间环节过多流出。不过公司目前正在组建专门的PR团队，人员正在招聘中，相信下一次JS大会一定会比这次更好，请给我们机会哈哈。

@treblam 非常抱歉，我们目前的工作人员有限，请再耐心等待，下一次我们一定会尽可能杜绝这类问题的发生，帮大家及时解决问题～希望继续支持我们的大会:)

**Comment by treblam** [comment]
@erqiudao 我现在就是希望这个问题能快速得到解决，现在好像还没有消息反馈给我是否人在处理我的问题。

**Comment by clairesheng** [comment]
@treblam 麻烦你直接把你的发票信息，收件地址给我吧 claire@wiredcraft.com

**Comment by treblam** [comment]
@clairesheng 邮件发了，请查收，用treblam@gmail.com这个账号发的。

**Comment by treblam** [comment]
@clairesheng 谢谢。
