### ISSUE TITLE
Goodies

### ISSUE THREAD

**Issue by quentinberder** [jsconfcn/ShenJS#4]
Putting together some goodies for the event.

**Tshirt**
I suggest we use a regular shape for the logo,because it's easy to do stickers.
![screen shot 2015-02-05 at 11 55 14 am](https://cloud.githubusercontent.com/assets/195066/6054832/e9fb4a5a-ad2d-11e4-8b22-3172b38cbb02.png)

**Pillows**
![screen shot 2015-02-05 at 1 55 27 pm](https://cloud.githubusercontent.com/assets/195066/6055668/cc4361d0-ad3e-11e4-940c-f5090e812d0a.png)

Could we make some pillow？
Claire said in hackshanghai they like it.It's cute  >_<

**Comment by erqiudao** [comment]
**Roll up banner**
We need many roll up banners to :1.guide 2.show schedule
Since we don't have schedule yet,so I made guide mockup first.

**V1**
The first version is using the landing page elements,blue background with illustrations and big texts.
the copy text is just a sample,we can discuss them later,for example maybe we need to add the address after we decide Venue.
![1369637467743](https://cloud.githubusercontent.com/assets/195066/6101498/4613d50c-b060-11e4-83b8-42e5ac12ed6d.png)

**V2**
The other option is using the logo element,as we know the logo is a square placeholder (window/browser/editor ),so we can put different parts of content in different placeholders, it looks not as formal as the first one,but it‘s more interesting. Also,the copy text is just sample, if we use is,we can add some geek slogan like "What the hack" "Mother forker" etc.
![1369637467743 copy2](https://cloud.githubusercontent.com/assets/195066/6101497/4610945a-b060-11e4-9f86-55f550570506.png)

**Comment by erqiudao** [comment]
**Pillows**
I think we can add slogan/tags on pillow / t-shirt / stickers to make it more personality and commemorative.
like cola does for their package.

![screen shot 2015-02-09 at 2 14 27 pm](https://cloud.githubusercontent.com/assets/195066/6101837/21520238-b066-11e4-82c8-8259148266b6.png)

What do you think and do you have some idea about the slogan/tags?

![screen shot 2015-02-09 at 2 25 54 pm](https://cloud.githubusercontent.com/assets/195066/6101917/9596fc7e-b067-11e4-8308-2b756e016990.png)

**Comment by erqiudao** [comment]
**E-Banner for Social media**
When we spread the news about ShenJS,we can do some banner like 
![screen shot 2015-02-09 at 12 36 17 pm](https://cloud.githubusercontent.com/assets/195066/6101932/e59a81f0-b067-11e4-993c-d8c3dabbf2ec.png)
After the scrum,now we need some kinds of information below.
1.Ask people to go to our public Github repo to discuss the ideas.
2.Call for speakers and sponsors
3.Subscribe the newsletters
anything else?

**Comment by z4rd** [comment]
I added a pinterest board and keep collecting, hope you can get some inspirations.

### https://www.pinterest.com/z4rd/js-conf/

and later I will find some pic of past tech conference on flickr, and add to this board.

Some points:

##### 1."the keyword wall" or ''the truth wall"

can be a hot frame, a new product, a company, a speaker's name..
encourange people comment on it.
![image](https://cloud.githubusercontent.com/assets/6663547/6106083/3ea19dd4-b099-11e4-922d-b19e25fdaf84.png)

##### 2.Badge can be provide with lot of little gifts(sticker, note pad, fridge magent, bookmark ...)

![image](https://cloud.githubusercontent.com/assets/6663547/6106688/8c3a1e18-b09e-11e4-8388-3170586381a2.png)

##### 3.booths

Base on the experience of music festival, booth can have different function:
A Welcome&infomation booth(lost and find)
A eat&drink booth
A second-hand transations & souvenir sell booth
A recruitment booth, for the supply and demand(with display screen).
A works show for participants(with display screen).

and I think this can replace company's booth or make the sponsors contract this,
to make them have the sense of participation.
All we need may be banner & table & maybe more staff(can be volunteer).

//other suggestions

##### -Encourange team wear their team's tee. spnonsor have a better area to seat.

##### -The weak light may have more atmosphere

##### -Area for rest & coding & eating if possible.

##### -Provide speaker a highchair, whether they use or not.

**Comment by erqiudao** [comment]
yeah~Badge
yesterday I thought maybe we can use different badge for people and speakers.
speakers use blue people use white
so speakers are easy to recognize when they are social but not on the stage.

**Comment by erqiudao** [comment]
and even pink for girl developer  233333333333
Jan and xeodou's girlfriend will have pink badge, so cute. >_<

**Comment by erqiudao** [comment]
**E-Banner for Social media**
I'm doing some GIF for advertise,we can use them for weibo/twitter.
I'm thinking doing
1.the generation of ShenJS logo
2.Call for speakers and sponsors
3.Subscribe the newsletters
Here is a example.
![comp-4](https://cloud.githubusercontent.com/assets/195066/6142785/6bc71cf2-b1f8-11e4-8f1b-3d87596c0e4c.gif)

**Comment by erqiudao** [comment]
![comp-5](https://cloud.githubusercontent.com/assets/195066/6143583/5ecc791c-b206-11e4-8c6a-0f5db02db13d.gif)

**Comment by erqiudao** [comment]
**for Wiredcraft**
The roll up banner we made last year only has our logo,lots of people coming to ask what we do,I remember Juha explaind some of them,and then we use a laptop to show our website career page.
But other companies  they did some printing for hiring and show their products.
So I suggest this year we can add hiring information on roll up banner.and make some stickers for our products to let people understand what we do and remember us.
![screen shot 2015-02-11 at 5 28 09 pm](https://cloud.githubusercontent.com/assets/195066/6144568/0862c74e-b214-11e4-842e-84a6b724ddc1.png)

**Comment by xeodou** [comment]
That's a good idea.  Last year we have beautiful banner but people don't know anything about us. They can't get too much things from banner

**Comment by erqiudao** [comment]
Example:
We can add copy text later
![1369637467743](https://cloud.githubusercontent.com/assets/195066/6144679/269a918c-b215-11e4-9fe5-73f16fdcd555.jpg)

**Comment by thoward** [comment]
@erqiudao Regarding your comment at (https://github.com/jsconfcn/ShenJS/issues/4#issuecomment-73640436) ... Please refrain from making comments about women that trivialize them. This creates an unwelcome environment for women engineers. 

We will **absolutely NOT** make pink badges for women. 

Also, please to do not imply that the women who attend are programmer's girlfriends. The women who attend are engineers. They are not children and do not need cute things. They need technical information, respect, and an environment where they feel comfortable and are not implicitly demeaned. 

This kind of language and attitude will not be tolerated in the JsConf.cn community.

**Comment by thoward** [comment]
Generally, regarding swag: IMO a t-shirt to commemorate and remember the event, and some stickers for people's laptops will be enough. 

We should be careful about what swag we produce. We don't want to make things that people don't really like or need. We want to make things that will be viewed as cherished items to remember the experience, not a pile of boring junk with our logos on it. If the attendees view the swag items as uninteresting, then toss them in the trash, the logo is now being associated with trash. We don't want that association. 

These sorts of things are also an additional cost, so I would avoid producing them.

This relates to https://github.com/jsconfcn/ShenJS/issues/13 as well. If we are going to do something additional, IMO notebooks are more useful than things like pillows.

**Comment by bencrox** [comment]
@thoward I hope not getting to another extreme. We shall not AVOID pink badges as an option, let it be an open choice if we can. I can foresee many girl geeks picking the pink one, let them decide, so do the boys / man / transgender / minerals.

We do have kidults and we are not to penalise people's desire to be cute. This holds when a pillow do serve a warm intention. 

I do agree that we should be rational to not producing too much and making things not demanded. But are pillows bad? Ask the attendees during enrolment. Make decision with data, that is free enough.

**Comment by hunvreus** [comment]
I personally prefer not to generate too much potential garbage. Things like t-shirts, stickers and notebooks all have a direct usage and are rarely discarded. From experience, things like dolls, toys, keychains, etc, tend to be trashed.

Why don't we focus on the stuff we know we'll do (tees, stickers and maybe notebooks) and see if the community want more swag once we have other more pressing things figured out?

**Comment by bencrox** [comment]
Just 2 cents with my experience in organising BarcampHK. We made most things on demand, people paid for it when ticketing ( Barcamp itself is free, people donate as they like ). Only thing with 100+ people want it will be made.

**Comment by thoward** [comment]
@bencrox well, my point is that the color was being related to the gender, and that stereotypes about gender were being made in a blanket statement. The color itself doesn't matter. We can have pink badges, blue badges, orange badges, whatever.. in fact we can have all the colors and let people pick whatever they want. That's actually what I chose to do in previous years with t-shirts. But we won't have "this color for boys, that color for girls".

**Comment by erqiudao** [comment]
update
### Tee
![artboard 2](https://cloud.githubusercontent.com/assets/195066/7804835/56c4d9a8-039b-11e5-9dd5-82e6b1c8a187.png)
We want to do 4 color.
black & white for Participants
blue for Speakers
grey for Volunteer

graphic on the tee is base64 code 
![screen shot 2015-05-26 at 11 37 44 am](https://cloud.githubusercontent.com/assets/195066/7804886/057caf52-039c-11e5-849a-cf7b36132af6.png)

### badge
we don't want to use thick PVC card this year,we want to use thick kraft paper for better environmental protection. though the craft and cost maybe higher than before.
![screen shot 2015-05-26 at 11 43 39 am](https://cloud.githubusercontent.com/assets/195066/7804924/7d03cb00-039c-11e5-9447-2b21954c6af0.png)

### Sticker
![screen shot 2015-05-26 at 11 45 24 am](https://cloud.githubusercontent.com/assets/195066/7804948/c1735b0c-039c-11e5-9d1f-d66ae8009db8.png)

### Recycle Bags and notebook
![screen shot 2015-05-26 at 11 52 53 am](https://cloud.githubusercontent.com/assets/195066/7805024/dc7fddca-039d-11e5-92f9-bded36cda2a0.png)
These two are optional depends on budget.

**Comment by quentinberder** [comment]
We got all necessary. Closing.
