### ISSUE TITLE
Sign for a Wechat account

### ISSUE THREAD

**Issue by quentinberder** [jsconfcn/ShenJS#6]
We need to create a Wechat account to easily communicate with the future attendees.

**Comment by clairesheng** [comment]
Now we have the access to Weibo & Twitter. We should start to update our progress to inform and increase the followers. Can we publicize our potential venue, logo, T-shirt or pillow design, etc?

**Comment by quentinberder** [comment]
Hold on for a minute on this. Find first information on the Wechat and let's outline a communication plan.

**Comment by clairesheng** [comment]
Registered. Waiting for approval on 15th. Head photo and introduction information can be changed if necessary.

**Comment by quentinberder** [comment]
Done, closing.
