### ISSUE TITLE
Shortlist tech companies

### ISSUE THREAD

**Issue by quentinberder** [jsconfcn/ShenJS#7]
- Tencent
- Xunlei
- Kuaibo
- [KnewOne](http://knewone.com/)
- [悠米(深讯和科技)](http://www.sxmobi.com/)
- [Zealer](http://www.zealer.com/)
- [博雅互动](http://www.boyaa.com/)
- [无觅](http://www.wumii.com/)
- [BESTlab](http://www.besdlab.cn/#) On V2EX, a guy from BESTlab contacted me, and they are willing to help during the event.
- Eric Pan eric.pan@seeedstudio.com - Seeedstudio - He has been involved with us for the Drupal Tour in 2012, I will send him an email directly.

**Comment by quentinberder** [comment]
@clairesheng to add the information from the Hackpad.

**Comment by quentinberder** [comment]
https://wiredcraft.hackpad.com/Shenzhen-JS-collaboration-contact-FyPadwdfcVQ

**Comment by frankdou** [comment]
[深圳市微智云科技](http://yunba.io/)
[华为](http://www.huawei.com/cn/)
[糗事百科](http://www.qiushibaike.com/)
[脸萌](http://www.bqtalk.com/indexP.html)
[大疆创新](http://www.dji.com/cn/company)
[coding.net](https://coding.net/home.html)
[XMind](http://www.xmind.net/)

**Comment by erqiudao** [comment]
frank么么哒

**Comment by hunvreus** [comment]
@frankdou When are you paying us a visit?

**Comment by frankdou** [comment]
@erqiudao   :)
@hunvreus ......

**Comment by clairesheng** [comment]
With your girlfriend @frankdou

**Comment by meggery** [comment]
- UC (in Guangzhou)
- Jinshan (in Zhuhai)
- Meizu (in Zhuhai)  
  They are not far from Shenzhen.
- 微拍
- 小恩爱

**Comment by bencrox** [comment]
DECORIS Intelligent System   迪科飾  ( SZ ) 
- 智能門鈴，有 json API ，示範室在崗廈

Web fusion Technology Limited   緯訊科技  ( HK / 上海 ) 
- 保安、電話、SMS、設備和人員管理坪台，

Home Run Mobile Facades 鴻運移動模組 ( HK / 台灣 / 珠海 ) 
- 創意集裝箱商務，空間設計

Vernant Society  春暉學社 ( HK ) 
- 私人教學機構，為創新公司訓練人才，總部在香港新界大埔／火炭

Startup Commune 創業公社 ( HK ) 
- 為香港創業公司作各方面的支援服務，包括火炭工業區的租務、各種活動、商務文書、集資

Across Asia Strategy 越亞策略 ( HK / SF / 台南 / 緬甸) 
- 專門做公關業務，協助創業公司走進亞洲各地

以上都是我名下的部份公司，雖然業務很不同，但都是集中用 JS 開發系統和中間件的。
不相關就不列出了。

**Comment by prigara** [comment]
Hi, @quentinberder! I, on behalf of [JetBrains](https://www.jetbrains.com/) would like to offer a couple of WebStorm personal licenses for a raffle at the event. Please ping me at ekaterina.prigara(at)jetbrains.com if you're interested. Thanks!

**Comment by xeodou** [comment]
@prigara Awesome !!!!

**Comment by quentinberder** [comment]
Done, closing.

**Comment by prigara** [comment]
Not sure whether you're interested and sent me an email, but just to let you know I haven't received any.

**Comment by quentinberder** [comment]
Could you send back one? We had issues last month with our mailbox.

**Comment by xeodou** [comment]
@quentinberder I am already taking care of this.
