### ISSUE TITLE
Main international events and conferences

### ISSUE THREAD

**Issue by quentinberder** [jsconfcn/ShenJS#8]
In order to pick up a date we need to take into account the main international events and conferences. This will allow us to get better international profiles.

| Event | Date |
| --- | --- |
| [NodeConf](http://nodeconf.com/) | 8-9 June |
| [NodeConf EU](http://nodeconf.eu/) | 7-11 September |
| [JSConf US](http://2015.jsconf.us/) | 27-29 May |
| [JSConf EU](http://2015.jsconf.eu/) | 25-27 September |
| [react-europe](http://www.react-europe.org/) | 02-03  July |

**Comment by quentinberder** [comment]
How does July 11-12 sounds like? Does it conflict with anything in China?

**Comment by xeodou** [comment]
Sounds good.  Let's check the big event in China

**Comment by xeodou** [comment]
Maybe middle of June before the Dragon Boat Festival ? 6. 13/14

**Comment by clairesheng** [comment]
HTML5 Conference June in Shanghai 1500 people, August in Beijing 4000 people. More of carnival.
http://mp.weixin.qq.com/s?__biz=MjM5NDY3MzMwMA==&mid=206460309&idx=1&sn=836a65b50216ba35ec6c34999b7dc01f&scene=1&key=e50c042086dc9717c1d52518605bd2b56b5d3da25fa794f7370c18ab35ff42331fd5affad86ea1fcf98556657c1b62b8&ascene=1&uin=MjY1MzY5OTU%3D&devicetype=Windows+7&version=61000713&pass_ticket=%2FPR1FCrnIQ7p0%2BBgSSh2J7UxExfNbGAMMYTCB85i3qE%3D

**Comment by bencrox** [comment]
JSConf HK , looking for mid Oct 2015

**Comment by quentinberder** [comment]
Done, closing.
