### ISSUE TITLE
Topics

### ISSUE THREAD

**Issue by fraserxu** [jsconfcn/ShenJS#9]
Proposal topics:
- io.js(Nodejs)
- ES6(6to5, koajs)
- Front-end frameworks(Reactjs, Angularjs)
- Real time communication(WebRTC, xmpp-ftw)
- Node-bots(arduino, Johny Five)
- Cross platform development(react native, node-webkit, atom-shell, phonegap, ionic)
- Mad science(torrent, dat)

**Comment by glennblock** [comment]
Microservices?

**Comment by glennblock** [comment]
NodeOS

**Comment by leizongmin** [comment]
tessel & hardware?

**Comment by jiangplus** [comment]
npm
blockchain, crypto currency
meteor

**Comment by mattma** [comment]
My name is Matt Ma. I am the author of [ember-rocks](https://github.com/mattma/ember-rocks).

**ember-rocks** is a web's scaffolding tool for building ambitious modern web application just like [Yeoman](http://yeoman.io/). It uses **ES6** module loader system to wire up the client side code, which utilized [Ember.js](http://emberjs.com/) MVC framework. User could quickly start a project, write future **ES6** code, pre-compile to vanilla **ES5** code in development time via [Babel](https://babeljs.io/), renamed from [6to5] project. There are lots of other cool features, [click here to read more](https://github.com/mattma/ember-rocks/blob/master/README.md),

Server side framework currently uses **Express**, but I am trying to migrate into **Koa**, ([see the progress here](https://github.com/mattma/koa-rocks)) when **io.js** reaches its stabilizing releases (production ready stage).

There are lots of topics related to it that I could talk about, for example, **Ember.js**, which is not popular in China yet, but oppositely, it is pretty successful in US. **Isomorphic javascript**, **Cordova or PhoneGap integration** etc. If interested, ping me for more details.

**Comment by xeodou** [comment]
@mattma Move you commit to #14

**Comment by quentinberder** [comment]
Call for speakers is closed, and all topics are in the schedule.
